DROP DATABASE IF EXISTS planity_db;
CREATE DATABASE planity_db;
USE planity_db;

-- 1. TABLA USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO BIGINT NOT NULL AUTO_INCREMENT, -- Cambiado a BIGINT para coincidir con Java Long
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

	select * from usuario;

-- 2. TABLA PROYECTO
CREATE TABLE PROYECTO (
    ID_PROYECTO BIGINT NOT NULL AUTO_INCREMENT, -- BIGINT
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_USUARIO BIGINT NOT NULL, -- El creador (FK coincidente en BIGINT)
    PRIMARY KEY (ID_PROYECTO),
    CONSTRAINT FK_USUARIO_PROYECTO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

select * from proyecto;

-- 3. TABLA USUARIO_PROYECTO (Invitados)
CREATE TABLE USUARIO_PROYECTO (
    ID_USUARIO_PROYECTO BIGINT NOT NULL AUTO_INCREMENT,
    ESTADO VARCHAR(255) DEFAULT 'PENDIENTE',
    ID_USUARIO BIGINT NOT NULL,
    ID_PROYECTO BIGINT NOT NULL,
    PRIMARY KEY (ID_USUARIO_PROYECTO),
    CONSTRAINT FK_UP_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_UP_PROYECTO FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO),
    CONSTRAINT UNIQUE_UP_RELATION UNIQUE (ID_USUARIO, ID_PROYECTO) -- Evita duplicados
);

select * from USUARIO_PROYECTO;

-- 4. TABLA BLOQUE (Sprint)
CREATE TABLE BLOQUE (
    ID_BLOQUE BIGINT NOT NULL AUTO_INCREMENT, -- BIGINT
    NOMBRE VARCHAR(50) NOT NULL,
    FECHA_INICIO DATETIME,
    FECHA_FIN DATETIME,
    ID_PROYECTO BIGINT NOT NULL,
    PRIMARY KEY (ID_BLOQUE),
    CONSTRAINT FK_PROYECTO_BLOQUE FOREIGN KEY (ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO)
);

-- 5. TABLA TAREA
CREATE TABLE TAREA (
    ID_TAREA BIGINT NOT NULL AUTO_INCREMENT, -- BIGINT
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION TEXT,
    ESTADO VARCHAR(20) NOT NULL DEFAULT 'TODO',
    ID_BLOQUE BIGINT NOT NULL,
    ID_USUARIO BIGINT, -- Puede ser NULL si nadie la tiene asignada
    PRIMARY KEY (ID_TAREA),
    CONSTRAINT FK_BLOQUE_TAREA FOREIGN KEY (ID_BLOQUE) REFERENCES BLOQUE (ID_BLOQUE),
    CONSTRAINT FK_TAREA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

-- 6. TABLA SUBTAREA
CREATE TABLE SUBTAREA (
    ID_SUBTAREA BIGINT NOT NULL AUTO_INCREMENT, -- BIGINT
    NOMBRE VARCHAR(50) NOT NULL,
    HORA DATETIME,
    DESCRIPCION TEXT,
    ESTADO VARCHAR(20) DEFAULT 'PENDIENTE',
    ID_TAREA BIGINT NOT NULL, -- FK a la tarea padre
    ID_USUARIO BIGINT,
    PRIMARY KEY (ID_SUBTAREA),
    CONSTRAINT FK_TAREA_SUBTAREA FOREIGN KEY (ID_TAREA) REFERENCES TAREA (ID_TAREA),
    CONSTRAINT FK_USUARIO_SUBTAREA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);